name: Model Training
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.1.1-base
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        pip install torch==2.1.2+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
        pip install transformers datasets
    - name: Start Training
      run: |
        chmod +x train.sh
        ./train.sh
